# Generated by Django 4.1.1 on 2022-09-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
