# Generated by Django 4.1.1 on 2022-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_siteemail_delete_siteimage_delete_sitelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='moto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='info_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='sales_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='support_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
